### ISSUE TITLE
Not able to parse the code using any parse function

### ISSUE THREAD

**Issue by ankur-1989** [SrTobi/escalima#2]
I am trying to parse a JS file contains following code using parseScript method
// Life, Universe, and Everything
function main() {
  return 'HELLO, WORLD!';
}

main();
but it gives me an error - 
Exception in thread "main" escalima.ESPrimaParseException: Error: Line 1: Unexpected identifier in <eval> at line number 2003 at column number 9
	at escalima.JVMESPrimaBridge.parse(JVMESPrimaBridge.scala:24)
	at escalima.ECMAScript.parseScriptToJson(ECMAScript.scala:59)
	at escalima.ECMAScript.parseScript(ECMAScript.scala:35)
	at de.upb.cs.swt.delphi.jsanalyzer.Main$.delayedEndpoint$de$upb$cs$swt$delphi$jsanalyzer$Main$1(Analyzer.scala:23)
	at de.upb.cs.swt.delphi.jsanalyzer.Main$delayedInit$body.apply(Analyzer.scala:12)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at de.upb.cs.swt.delphi.jsanalyzer.Main$.main(Analyzer.scala:12)
	at de.upb.cs.swt.delphi.jsanalyzer.Main.main(Analyzer.scala)

**Comment by SrTobi** [comment]
Hmm that's really curious. Unfortunately I'm not able to reproduce the error... The following code works fine for me:

```scala
val ast.Program(_) = emcaScript.parseScript(
            """
            |// Life, Universe, and Everything
            |function main() {
            |   return 'HELLO, WORLD!';
            |}
            |main();
            """.stripMargin)
```

The error message is normal, as the internal exception is always thrown by esprima in line 2003 at column number 9.

Could you maybe provide some more information about your code? And are you really sure that the `//` is present in the string you are sending to `parseScript`? Did you try other code snippets? did they work or not?

**Comment by ankur-1989** [comment]
Please find below my complete code and test.js file contains the javascript code that i pasted above. It was working for "t=10" expression but when i give multiple expression it again gives error.


import escalima.ECMAScript;
import scala.io.Source;

import escalima.ast;
import escalima.ast.SpreadableExpression;
import upickle.json;
import ujson.Js;
import net.liftweb.json._
import escalima.ESPrimaParseException
import javax.script.{Invocable, ScriptEngineManager, ScriptException}

object Main extends App {
  
  //Reading a JS source file
  val code =  Source.fromFile("test.js");

  val parser = new ECMAScript;
  try{
  val asTree = parser.parseScriptToJson(code.toString());  
  }
  catch {
    case e: ScriptException =>
        e.printStackTrace();
  }
  
  
}

**Comment by SrTobi** [comment]
The problem is that `code.toString()` returns the string `"<iterator>"` and not the actual content of the file.

Use the following expression to load a file into a string

```
Source.fromFile("test.js").getLines.mkString("\n")
```

**Comment by ankur-1989** [comment]
I found the issue, Sorry for the trouble. Issue was with the file reading only. Thanks for your help. I need one more information. In Esprima, we have option to add comments as well in parse function but i did not see the option here.

**Comment by SrTobi** [comment]
I know what you mean... unfortunately there is no option to do that at the moment. That's definitely something that is missing.

I opened a new issue #3 to address that. I first have to look at how to integrate that nicely, though.

**Comment by ankur-1989** [comment]
Thanks :)

**Comment by SrTobi** [comment]
@ankur-1989 do you want to use the `parseScript` or the `parseScriptToJson` method?

For the later one, it should be fairly easy to add the comment parsing.

**Comment by ankur-1989** [comment]
@SrTobi Yes I want to use these methods , have you integrated it for later one?

**Comment by SrTobi** [comment]
No, sorry. I'm currently on holiday... I will look into it when I'm back
